### ISSUE TITLE
Extension icon invisible in light mode

### ISSUE THREAD

**Issue by mattots** [gabrielmaldi/chrome-lock-tab#1]
In light mode, the extension icon is completely invisible:

<img width="180" alt="image" src="https://user-images.githubusercontent.com/301729/188097852-2ccd9bf0-28c8-4d34-b2d2-c2ba6503d04c.png">

It only shows up (faintly) on mouseover:

<img width="182" alt="image" src="https://user-images.githubusercontent.com/301729/188098012-3de37b42-ed1c-4ac4-899c-6b77e3aa7518.png">

**Comment by gabrielmaldi** [comment]
Thanks for reporting!

I just submitted an update to the Chrome Web Store which adds support for light and dark color-scheme icons.

<img width="295" alt="Screen Shot 2022-09-02 at 18 40 33" src="https://user-images.githubusercontent.com/3728897/188239510-88822837-abc3-48d7-b341-b4e92eea4370.png">
<img width="296" alt="Screen Shot 2022-09-02 at 18 40 39" src="https://user-images.githubusercontent.com/3728897/188239518-25e58f99-6533-4821-8481-69e3dc676a65.png">
<img width="288" alt="Screen Shot 2022-09-02 at 18 41 08" src="https://user-images.githubusercontent.com/3728897/188239566-9d5d0e7f-884e-48ba-ac36-3fe926bab4e5.png">
<img width="295" alt="Screen Shot 2022-09-02 at 18 41 16" src="https://user-images.githubusercontent.com/3728897/188239574-1cb39811-390a-4544-9cac-5b540b68a744.png">

It will go live automatically when approved.
