### ISSUE TITLE
Seems to only work on Github

### ISSUE THREAD

**Issue by sickerin** [gabrielmaldi/chrome-lock-tab#2]
This only seems to work on github for me. 
Chrome: Version 107.0.5304.110 (Official Build) (x86_64)
MacOS: Monterey 12.4

**Comment by sickerin** [comment]
Hey, @gabrielmaldi thanks for replying. After trying a few things u suggested, it seems to be working now!

**Comment by gabrielmaldi** [comment]
Great! Thanks for using Lock Tab ♥️
