### ISSUE TITLE
No 'Lock' in context menu

### ISSUE THREAD

**Issue by terrypin999** [gabrielmaldi/chrome-lock-tab#5]
Same for any tab. Restart of Chrome didn't fix.

**Comment by gabrielmaldi** [comment]
Hi, Terry. Lock Tab does not want to pollute (the already polluted) context menu. So you can toggle the locked/unlocked state of a tab from the extension icon in the browser's top-right corner. Here's a GIF explaining this. Thanks!

![usage](https://user-images.githubusercontent.com/3728897/212362793-412ddba8-a5ca-42ad-acd0-d8d50c62f97d.gif)
