### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by Bassadin** [gabrielmaldi/chrome-lock-tab#8]
I'm on Chrome 124.0.6367.207 - clicking the lock icon doesn't seem to do anything. Can I debug this somehow to get you a log or something? I have no experience with developing Chrome extensions, unfortunately.

**Comment by gabrielmaldi** [comment]
Hi, thanks for the feedback!

Does it fail on every website? If it does, you can open the Chrome Developer Tools and select Lock Tab in the Console tab:

<img width="235" alt="image" src="https://github.com/gabrielmaldi/chrome-lock-tab/assets/3728897/783d3db7-48f6-4bef-b044-490fc19b348e">

Error should be logged there.

Also, you can browse `chrome://extensions` and see if Lock Tab has an `Error` button which you can click to see more information:

<img width="420" alt="image" src="https://github.com/gabrielmaldi/chrome-lock-tab/assets/3728897/f7ed1ecf-1e68-4545-a6ad-c712e5c90638">
